image:
- Visual Studio 2017

stack: python 3

build: off

environment:
  PY_DIR: C:\Python36-x64  # FIXME: py37 waiting scikit-image

clone_depth: 3

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
- pip install -e .[tests]
  
test_script:
- pytest -sv

