language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
  - 3.6
#  - 3.7  # FIXME: scikit-image whl

os:
  - linux

install: pip install -e .[tests]

script:
  - pytest -sv
  - flake8
#  - mypy . --ignore-missing-imports  
# waiting for new Python release, per my bugfix 
# https://github.com/python/typeshed/pull/2194

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

